### ISSUE TITLE
debug发现是720*1480，系数为2.05,但还是出错

### ISSUE THREAD

**Issue by xwpeng** [burningcl/wechat_jump_hack#10]
1.手机三星s8。
2.可调分辨率到720*1480，设置系数为2.05f。
3.运行报错，日志。
find myPos, succ, (223, 852)
172, 174, 183
227, 231, 241
top, x: 718, y: 416
false
left, x: 2147483647, y: 2147483647
right, x: -2147483648, y: 2147483647
java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
4.请问实现原理还有其他因素影响吗？
5.debug短时间找不到问题。

**Comment by burningcl** [comment]
更新一下代码，我在晚饭时间修复了这个问题

**Comment by xwpeng** [comment]
正常手机是720 * 1280，全面屏高度会高一点是720 * 1480。改进成根据截图的图片宽高自动设置弹跳系数就完美了。
比如1080 * 1920 全面屏是1080 *2220.
不知道我的理解对不。

**Comment by burningcl** [comment]
我现已经改为，可以适应各种屏幕尺寸了。

**Comment by burningcl** [comment]
现在效果怎么样？？

**Comment by xwpeng** [comment]
用了新代码，直接运行，跳得很远。

**Comment by burningcl** [comment]
擦。。。
那你干掉自适应的那一段代码，然后重新运行一下看看。
