### ISSUE TITLE
个别图形识别还是存在问题

### ISSUE THREAD

**Issue by tenwx** [burningcl/wechat_jump_hack#102]
见标注图
![29](https://user-images.githubusercontent.com/3733304/38775492-829118b6-40b6-11e8-8d79-1d6f408ce997.png)
![39](https://user-images.githubusercontent.com/3733304/38775494-88ddfefa-40b6-11e8-97d1-b740e983a6ad.png)
![19](https://user-images.githubusercontent.com/3733304/38775499-a4798b52-40b6-11e8-9cc7-807f7aaa6f1c.png)
感觉应该是碰到纹理复杂些的图识别就好存在误判

**Comment by tenwx** [comment]
继续补充
![9](https://user-images.githubusercontent.com/3733304/38777141-8f6564ec-40d5-11e8-8b81-03ba09487a16.png)
![4](https://user-images.githubusercontent.com/3733304/38777144-96aea09c-40d5-11e8-80ac-60aa6b21cce3.png)

**Comment by burningcl** [comment]
应该是最近新加了很多道具，你可以自己改一下算法看看
