### ISSUE TITLE
ADB建议

### ISSUE THREAD

**Issue by fansmc** [burningcl/wechat_jump_hack#13]
跑起来了，没毛病，关于reme中的adb路径，建议直接在环境变量中配置下adb ，然后Hack。java文件中直接把ADB_PATH 的值改为“abd” 就行了
配好adb 的环境变量后 打开cmd 测试下 输入“adb shell” 命令 ，cmd中显示你连接的手机名称：/$ 就可以了

**Comment by fansmc** [comment]
补充下， adb后面要加个空格

**Comment by ckuire** [comment]
补充下，今天驱动一切正常，但是adb死活连不上，adb devices没有设备，最后发现adb工具包有问题，建议在http://adbshell.com/downloads下载，第一个是工具包，第二个可以直接安装驱动？（小白一个，逃

**Comment by absentm** [comment]
『 495 分 』, Perfect，ADB 环境变量配置请参考：[Windows10 Android adb 环境变量配置](https://absentm.github.io/2018/01/04/Windows10-Android-adb-%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E9%85%8D%E7%BD%AE/)
