### ISSUE TITLE
作为一个纯新人，想问你一下走到这一步然后呢

### ISSUE THREAD

**Issue by Fzyfeng** [burningcl/wechat_jump_hack#15]
![image](https://user-images.githubusercontent.com/23629370/34551700-36ec3516-f157-11e7-9924-fb0922146295.png)

**Comment by burningcl** [comment]
请仔细阅读README

**Comment by burningcl** [comment]
最好用java ide而不是android的ide

**Comment by Fzyfeng** [comment]
是啊我用的IntelliJ ，现在已经克隆下来了，不知道怎么import。。。我现在用IntelliJ创建了一个安卓的项目不知道下一步怎么做了 
麻烦指教，百度了好多没说怎么import

**Comment by burningcl** [comment]
看一下这个
https://www.zhihu.com/question/38595887

**Comment by Fzyfeng** [comment]
![123](https://user-images.githubusercontent.com/23629370/34553871-c895ca2e-f164-11e7-9fb6-52aad74e001a.png)
选的maven然后就酱紫了

**Comment by absentm** [comment]
IDEA Import Project, 选择 eclipse module .

**Comment by Fzyfeng** [comment]
@absentm  没有的啊
![2333](https://user-images.githubusercontent.com/23629370/34556243-91ce5de2-f170-11e7-9cc1-f4f3b08fec6d.png)

**Comment by xwpeng** [comment]
新建java项目，复制几个java文件到src，跑起来就ok了。

**Comment by Fzyfeng** [comment]
@xwpeng 我复制了几个.java 文件进到楼主的项目src里还是不行啊

**Comment by absentm** [comment]
@Fzyfeng ，用的 IDEA 2017.2.1 版本可以。

**Comment by Fzyfeng** [comment]
@absentm  又没法上传截图了 我用的2017.3.1

**Comment by absentm** [comment]
@Fzyfeng，看看这个，https://github.com/burningcl/wechat_jump_hack/blob/master/IMPORT.md

**Comment by Fzyfeng** [comment]
@absentm  大神就差最后一步了 
运行程序（Hack.java中的main方法）
没耍过java不知道咋让他运行

**Comment by burningcl** [comment]
文件 没有被拉下来，你先改一下 Runtime.getRuntime().exec(ADB_PATH + " pull /sdcard/screenshot.png " + file.getAbsolutePath());后面的sleep时长，我后续会改进实现。

**Comment by Fzyfeng** [comment]
@burningcl Thread.sleep()对吧 改多少？
另外问一2次跳跃的时间间隔再哪行，我要去改个随机数。。。

**Comment by burningcl** [comment]
sleep(4_000)这一行
我已经改掉了，午休时间 会上传

**Comment by Fzyfeng** [comment]
@burningcl 哥，看下问题，我把时间间隔改成了4000 还是报这个错
![image](https://user-images.githubusercontent.com/23629370/34593598-d20b3f24-f206-11e7-9110-9189689d8231.png)
是这样的吧？

**Comment by burningcl** [comment]
https://github.com/burningcl/wechat_jump_hack/blob/master/IMPORT.md
看这个文档
确认第6-7步

**Comment by Fzyfeng** [comment]
@burningcl emmm数据线问题，刚才测了一下遇到黑色圆形盘子跳不到上面去

**Comment by burningcl** [comment]
还用这事，，，需要换个好的数据线？？

**Comment by Fzyfeng** [comment]
@burningcl 数据线这个是我特例啊，，你咋给人回了呢，我的接口不好只能充电不能传数据才换的。。。
