### ISSUE TITLE
腾讯限制上传分数，有没有解决的办法，已经知道固定时间的是无法上传分数的

### ISSUE THREAD

**Issue by huangyichun** [burningcl/wechat_jump_hack#19]
通过随机时间成功了一个780的，之后换了一个手机就不行了

**Comment by huangyichun** [comment]
腾讯限制上传分数，有没有解决的办法，已经知道固定时间的是无法上传分数的

**Comment by burningcl** [comment]
道高一尺，魔高一丈。哈哈

**Comment by kelingv5** [comment]
“已经知道固定时间的是无法上传分数的”什么意思

**Comment by huangyichun** [comment]
每次跳的时间间隔是一样，是无法上传分数的

**Comment by burningcl** [comment]
https://github.com/burningcl/wechat_jump_hack/blob/master/IMPORT.md
