### ISSUE TITLE
导入找不到wechat_jump_hack.iml文件

### ISSUE THREAD

**Issue by yangyiRunning** [burningcl/wechat_jump_hack#24]
RT

**Comment by burningcl** [comment]
https://github.com/burningcl/wechat_jump_hack/blob/master/IMPORT.md

**Comment by burningcl** [comment]
如果觉得跳得不准的同学，请运行HackTest.java文件，观察标记的位置是否准确。如果准确的话，请自行调整弹跳系数。笔者无法做到我所用的弹跳系数适用于所有的设备。
