### ISSUE TITLE
启动时，IO异常，自定义的ADB_PATH路径拒绝访问

### ISSUE THREAD

**Issue by kelingv5** [burningcl/wechat_jump_hack#25]
java.io.IOException: Cannot run program "E:\base\platform-tools": CreateProcess error=5, 拒绝访问

**Comment by luweicheng24** [comment]
@kelingv5 你的解决了吗?我也出现这个问题啊

**Comment by burningcl** [comment]
https://github.com/flutter/flutter-intellij/issues/1015

**Comment by kelingv5** [comment]
@luweicheng24 路径后面加上adb即可

**Comment by lihhwork** [comment]
我也遇到同样问题，后面看来是图省事把adb放在了用户目录下，然后没有足够的权限执行。把adb放在其他地方就可以了

**Comment by Liby94** [comment]
不知道你们和我的问题 一样不，在hack.java中有 static final String ADB_PATH = "/Users/chenliang/Library/Android/sdk/platform-tools/adb"; 这段代码，把这个改成你adb所在的路径，我的是static final String ADB_PATH = "D:\\android-sdk\\platform-tools\\adb"; 然后这个错误就解决了
