### ISSUE TITLE
find myPos, fail

### ISSUE THREAD

**Issue by Evanhlx** [burningcl/wechat_jump_hack#3]
root: /E:/0DvelopePrograms/wechat_jump_hack/out/production/wechat_jump_hack/
srcDir: E:\0DvelopePrograms\wechat_jump_hack\out\production\wechat_jump_hack\imgs\input
screenshot, file: E:\0DvelopePrograms\wechat_jump_hack\out\production\wechat_jump_hack\imgs\input\0.png
find myPos, fail

Process finished with exit code 0

**Comment by burningcl** [comment]
首先，看一下E:\0DvelopePrograms\wechat_jump_hack\out\production\wechat_jump_hack\imgs\input\0.png这个文件存在不。
如果不存在，则说明你的adb没有连好你的手机。
如果存在的话，请把图片发给我，我来看看。

**Comment by fuliteng** [comment]
或者改下休眠时间

**Comment by fuliteng** [comment]
或者改下休眠时间，机器有时候反应不过来

**Comment by burningcl** [comment]
你可以在你本地调整一下试试

**Comment by burningcl** [comment]
已经处理，更新代码
