### ISSUE TITLE
先解决怎么把分数上传到排行榜才是王道

### ISSUE THREAD

**Issue by kevinvane** [burningcl/wechat_jump_hack#30]
现在的分数只能在自己的排行榜停留，别人没有，强行停止微信，再重新打开就没了。

**Comment by Fzyfeng** [comment]
我听说换一个随机跳跃间隔的时间就行了
hack代码最下面try你换成这个试试
Random random = new Random();
                int sleepTime = random.nextInt(1000);
                Thread.sleep(sleepTime);

**Comment by burningcl** [comment]
https://github.com/burningcl/wechat_jump_hack/blob/master/IMPORT.md
