### ISSUE TITLE
弹跳系数是怎样得来的，在高分辨率的手机上跳不准。

### ISSUE THREAD

**Issue by wangyiyong** [burningcl/wechat_jump_hack#32]

**Comment by burningcl** [comment]
你手机是什么分辨率的

**Comment by Jimmuy** [comment]
我手机分辨率也不准  mix2  2160*1080

**Comment by wangyiyong** [comment]
荣耀V9分辨率是2560x1440

**Comment by Jimmuy** [comment]
求告知怎么计算 的弹跳系数

**Comment by Fzyfeng** [comment]
红米note4x，1920*1080跳不准，感觉我的手机最low  hhh

**Comment by burningcl** [comment]
如果觉得跳得不准的同学，请运行HackTest.java文件，观察标记的位置是否准确。如果准确的话，请自行调整弹跳系数。笔者无法做到我所用的弹跳系数适用于所有的设备。
