### ISSUE TITLE
的却可以自娱自乐，只是本地显示跳了多少进行排名。朋友卷其他人根本还是手动跳的分数

### ISSUE THREAD

**Issue by luweicheng24** [burningcl/wechat_jump_hack#37]

**Comment by burningcl** [comment]
官方新增了时间间隔检测，固定时间间隔的跳跃会无法上传，已更新随机数， 可以上传分数。保守一点，就是等跳得差不多了，自己在手动跳几下。

分数别刷太高；
最后自己再跳几下；

https://github.com/burningcl/wechat_jump_hack/blob/master/IMPORT.md
