### ISSUE TITLE
小米5 MIUI没有任何效果

### ISSUE THREAD

**Issue by 123ufo** [burningcl/wechat_jump_hack#4]
root: /I:/Github3/WeCharJup/lib/build/classes/java/main/
srcDir: I:\Github3\WeCharJup\lib\build\classes\java\main\imgs\input
screenshot, file: I:\Github3\WeCharJup\lib\build\classes\java\main\imgs\input\0.png
373, 298
pos, x: 335, y: 1129
find myPos, succ, (335, 1129)
172, 174, 183
228, 232, 242
top, x: 787, y: 719
true
left, x: 587, y: 835
right, x: 986, y: 832
find nextCenter, succ, (786, 833)
distance: 747
D:\android_studo_1.4\AS_ASK_1.4\platform-tools//adb shell input swipe 400 400 400 400 747
screenshot, file: I:\Github3\WeCharJup\lib\build\classes\java\main\imgs\input\1.png
373, 298
pos, x: 335, y: 1129
find myPos, succ, (335, 1129)
172, 174, 183
228, 232, 242
top, x: 787, y: 719
true
left, x: 587, y: 835
right, x: 986, y: 832
find nextCenter, succ, (786, 833)
控制台有输入.但是手机就是没反应

**Comment by 123ufo** [comment]
OK行了.

**Comment by burningcl** [comment]
cool

**Comment by dengxingwen** [comment]
同小米5 系数设置成1.45f非常爽

**Comment by zrui1991** [comment]
同小米5 系数设置成1.475 跳到了1103
