### ISSUE TITLE
关于位置识别算法的讨论

### ISSUE THREAD

**Issue by gaoyuke** [burningcl/wechat_jump_hack#40]
看样子作者是解析下一个位置的图形，获取此图形的中点和我的位置之间的距离？

**Comment by burningcl** [comment]
yes

**Comment by gaoyuke** [comment]
我有另外一个算法想跟你讨论一下，每次跳之前画面都会移动，然后左跳和右跳分别有两条固定的线，在这条线上识别可以提高下一个position的精确度。



172038488@qq.com
 
发件人： Jairus Chan
发送时间： 2018-01-05 16:06
收件人： burningcl/wechat_jump_hack
抄送： gaoyuke; Author
主题： Re: [burningcl/wechat_jump_hack] 关于位置识别算法的讨论 (#40)
yes

**Comment by burningcl** [comment]
最好能用图来说明一下，我没有听懂你的意思。

**Comment by gaoyuke** [comment]
每次跳完 我的位置肯定会落到这两根线的其中一根上， 你只需要去识别这条线上a、b点的中点m和我的位置的距离即可，不需要去管图形的形状。原形也跟这根线有两个交点。


172038488@qq.com
 
发件人： Jairus Chan
发送时间： 2018-01-05 16:34
收件人： burningcl/wechat_jump_hack
抄送： gaoyuke; Author
主题： Re: [burningcl/wechat_jump_hack] 关于位置识别算法的讨论 (#40)
最好能用图来说明一下，我没有听懂你的意思。

**Comment by burningcl** [comment]
你可以试试。
你也可以运行Hacktest.java看标记的位置准确不

**Comment by gaoyuke** [comment]
我不是做安卓开发的 = =



172038488@qq.com
 
发件人： Jairus Chan
发送时间： 2018-01-05 17:01
收件人： burningcl/wechat_jump_hack
抄送： gaoyuke; Author
主题： Re: [burningcl/wechat_jump_hack] 关于位置识别算法的讨论 (#40)
你可以试试。
你也可以运行Hacktest.java看标记的位置准确不
