### ISSUE TITLE
跳不到中心点的或者想刷高分的可以试试

### ISSUE THREAD

**Issue by fengzidk** [burningcl/wechat_jump_hack#45]
在计算出距离的代码那:
                        int distance = (int) (Math.sqrt((centerX - myPos[0]) * (centerX - myPos[0]) + (centerY - myPos[1]) * (centerY - myPos[1])) * jumpRatio);
int jian = (int)(RANDOM.nextInt(10));
                        System.out.println("随机减小距离:"+jian);
                        distance = distance-jian;
                        System.out.println("distance: " + distance);
随机减少距离0-10  可以增大中心点几率 30%左右,原理不明,可根据实际情况调整.
(ps: 本人每次刷分都只能在500份左右,每次都是跳过了OVER,在修正后,目前按分数已经700+了  未结束,看日志发现,每次距离修正7之后,中心点几率在70%以上.各位可以根据实际情况修正距离,不要修正JUMP_RATIO参数.理由是,每次的计算距离都是三位数,而偏差在10-20之前,修正距离能更安全的刷分), OVER...

**Comment by Suremotoo** [comment]
主要是 JUMP_RATIO，我试了，我手机是Vivo Y55和魅蓝5s，将系数调成 1.360后大大提升了跳中中心的概率，很快就上 500、600、上千都不会挂。
