### ISSUE TITLE
求参数讲解

### ISSUE THREAD

**Issue by SKYby18** [burningcl/wechat_jump_hack#47]
本人安卓小米5，最高跳到300多，但是再也没超过300了，想自己调整下参数，但是看不懂，所以恳请各位大神能不能讲解下项目运行所显示的参数

**Comment by hyxxy** [comment]
我三星s7e，需要改参数吗，第一步就不行了，直接飞出去。你改过参数没

**Comment by SKYby18** [comment]
现在可以了，我改了弹跳系数，你试试原来的1.390f测试，然后看它跳到300多分，然后修改成1.400f再测试，如果它比1.390跳得分数还多，那你可以尝试继续向上调整，反之则向下调整咯，就是做一个区间比较

**Comment by SKYby18** [comment]
现在还有个问题是，我想先测试弹跳系数，但是跳得太慢了，改了sleep时间结果死得更快

**Comment by burningcl** [comment]
你更新一下代码，现在只有一个sleep了。 那个sleep时间最小为2000ms。
