### ISSUE TITLE
adb shell input swipe 执行无效果

### ISSUE THREAD

**Issue by zcolin** [burningcl/wechat_jump_hack#48]
adb shell input swipe 执行无效果，需要root么？

**Comment by zcolin** [comment]
需要root么？

**Comment by limitlc** [comment]
不需要root,但是这个长按命令要安卓4.4以上才支持

**Comment by zcolin** [comment]
是安卓7.0，miui9, 红米note4x，截图啥的都行，这个命令没反应。

**Comment by dengkang** [comment]
华为P9 安卓7.0，adb连接没问题，但是执行截图命令 shell /system/bin/screencap -p /sdcard/screenshot.png没有反应，导致找不到图片报错

**Comment by burningcl** [comment]
你确定权限授权了吗？？
https://github.com/burningcl/wechat_jump_hack/blob/master/IMPORT.md
