### ISSUE TITLE
估计还要优化一下,每次到一百多的时侯就失败了.

### ISSUE THREAD

**Issue by 123ufo** [burningcl/wechat_jump_hack#5]
find nextCenter, fail

**Comment by burningcl** [comment]
1. 有些同学反馈，程序报错，提示找不到文件或者“find myPos, fail”。请确认是否adb已经联接上你的手机；如果adb连接失败，则会导致截图与拉取截图失败。
2. 有些同学反馈，位置都计算出来了，但是没有触发弹跳。打开开发者选项，找到“USB调试（安全设置）允许通过USB调试修改权限或者模拟点击”（在mui上是这样的，在其他手机上，应该也是差不多这样）这个开关，打开它。
3. 这个小游戏，后来腾讯好像加了一些干扰的动效，会干扰位置计算。后期可以优化。
4. 因为我总共才花了3小时去破解，主要的时间都花了前期的识别算法的优化上。代码中，还有很多魔法值什么的，代码也比较乱。如果要阅读的话，还请见谅。
5. 有同学反馈，跳几步就掉下去了。主要原因是弹跳系数的问题，我是根据我的自己的手机（1080p分辨率）来调试的。如果你的手机分辨率，不是1080p，则需要修改弹跳系数（JUMP_RATIO）。
6. 至于位置计算的准确性，请运行MyPosFinder.java与NextCenterFinder.java中的main方法，观察生成文件，查看标记的位置是否正确。

**Comment by 123ufo** [comment]
基本上都死在小药瓶这一步

**Comment by burningcl** [comment]
好吧，小瓶的识别，的确处理得不太好，后期可以优化。你现在可以跳到多少分了？

**Comment by 123ufo** [comment]
目前最高170 .再在再也超不过了.都死在110 到130之间

**Comment by burningcl** [comment]
运行截图，input目录中的png文件，放到src目录中，再运行一下MyPosFinder.java与NextCenterFinder.java中的main方法，观察生成文件，查看标记的位置是否正确。

**Comment by 123ufo** [comment]
我用Android Studio运行的.好像空引用异常,我把最后一张图片放到七牛上去了.你看看:http://og9p10hy3.bkt.clouddn.com/62.png

**Comment by burningcl** [comment]
运行截图，input目录中的png文件，放到src目录中，再运行一下MyPosFinder.java与NextCenterFinder.java中的main方法，观察生成文件，查看标记的位置是否正确。

**Comment by burningcl** [comment]
现在就两个可能的原因：1.位置识别有问题；2.弹跳系数有问题。
第一个原因，运行截图，input目录中的png文件，放到src目录中，再运行一下MyPosFinder.java与NextCenterFinder.java中的main方法，观察生成文件，查看标记的位置是否正确。
第二个原因，只能你自己调整系数了。

**Comment by burningcl** [comment]
如果觉得跳得不准的同学，请运行HackTest.java文件，观察标记的位置是否准确。 如果不准确的话，根据反馈同学的经验：

请自行调整弹跳系数；
换一根好一点的数据线； 笔者无法做到我所用的弹跳系数适用于所有的设备。

https://github.com/burningcl/wechat_jump_hack/blob/master/IMPORT.md
