### ISSUE TITLE
你好我想问一下我这个为什么运行不起来啊？

### ISSUE THREAD

**Issue by zhangrenliang1** [burningcl/wechat_jump_hack#51]
![ho 6kdf4j9q g75y 3c2](https://user-images.githubusercontent.com/35196198/34650946-43a16e3e-f404-11e7-8f09-9beb46a67a5c.png)

**Comment by burningcl** [comment]
http://blog.csdn.net/lyxtime/article/details/43372949
我就帮你google了，参考一下。^-^
