### ISSUE TITLE
不稳定情况

### ISSUE THREAD

**Issue by Suremotoo** [burningcl/wechat_jump_hack#55]
我的手机是魅蓝5s，最初的版本的时候，我还可以跳2000多分都不会挂，自从改了自适应屏幕后挂的概率很大。200、400、500都有挂的。

**Comment by burningcl** [comment]
你先删除那段代码，然后手动调整一下JUMP_RATIO试试

**Comment by Suremotoo** [comment]
多谢，我自己调试了下，1.360 极大跳中了中心点！很快就上千了。
