### ISSUE TITLE
系统找不到指定的文件

### ISSUE THREAD

**Issue by zengjiaozi** [burningcl/wechat_jump_hack#58]
\out\production\wechat_jump_hack-master\imgs\input\0.png (系统找不到指定的文件。)
会报这个错误 ，手机的设置都是正常的  adb连接也正常

**Comment by gaojinjin000** [comment]
先启动跳一跳，然后再运行java代码

**Comment by burningcl** [comment]
你更新一下代码再试试看。
另外，检查一下你的手机相册，有没有截图成功

**Comment by speedornothing** [comment]
我也遇到了类似的问题，我的解决方法是（游戏不退出）:   
```bash
$ adb devices
## 发现列出了多个设备（不正常）
$ adb kill-server
$ adb devices
## 杀掉服务端，然后再显示设备列表，这时只显示一个设备（正常），此时，重新执行 Hack#main 
```

参考 - http://blog.csdn.net/gaojinshan/article/details/9455193
