### ISSUE TITLE
分最高的是用的那款手机啊？

### ISSUE THREAD

**Issue by 06304322** [burningcl/wechat_jump_hack#60]
我这里最高才跳900多分。

**Comment by burningcl** [comment]
我的红米吧。
如果跳的分数不够。你可以这样做，如果跳近了，把JUMP_RATIO改大一些；如果跳远了，把JUMP_RATIO改小一些。
识别算法应该没有什么问题。但是JUMP_RATIO在不同的机器上表现不一样。
我试了几个机器，的确如此。
