### ISSUE TITLE
运行不成功

### ISSUE THREAD

**Issue by Yiny123** [burningcl/wechat_jump_hack#61]
Cannot run program "D:/android2.2andsdk/sdk/platform-tools": CreateProcess error=5, 拒绝访问。

**Comment by Dragon-Boat** [comment]
权限不够，尝试配置管理员权限

**Comment by Junlist** [comment]
……这个问题我思考了一天，作者说的是权限问题。然后我自己发现自己根本不是这个问题。 ADB_PATH那里不能只是指向文件夹，我指向adb.exe文件就成功了。……感觉自己好小白

**Comment by burningcl** [comment]
要指向adb文件，而不是adb目录。
