### ISSUE TITLE
关于adb命令截图

### ISSUE THREAD

**Issue by Laiyu777** [burningcl/wechat_jump_hack#63]
用的小米，
`Runtime.getRuntime().exec(ADB_PATH + " pull /sdcard/screenshot.png " + file.getAbsolutePath());`
发现有的时候截图在手机端上的图片会加上截图的时间(**_+毫秒)，
导致，adb的命令会报错找不到scard卡中的这张图片
有的时候却不会，很费解

**Comment by kevinvane** [comment]
红米4，没有发现这个问题，但发现，原来adb截图所有图片都保存在sd卡上(不是覆盖)，正在删图片...

**Comment by burningcl** [comment]
更新代码，已经处理了。
