### ISSUE TITLE
find nextCenter, fail

### ISSUE THREAD

**Issue by lOCKemM** [burningcl/wechat_jump_hack#66]
adb已经连接

```
> adb shell
* daemon started successfully *
HWFRD:/ $
```
ADB_PATH 配置如下

 static final String ADB_PATH = "Users/lockem/AppData/Local/Android/android-sdk/platform-tools/adb";

是哪里出了问题？华为荣耀8

**Comment by lOCKemM** [comment]
感觉应该是ADB_PATH的问题

**Comment by burningcl** [comment]
后来搞定了吗

**Comment by myjke123** [comment]
请问下我的也是io接口adb找不到路径的问题，用git GUI和git bash 都clone过放进但是还是一直运行不了？本人小白第一次接触idea今天下了一下午各种软件感觉都搞到最后就是运行不了，求助一下

**Comment by burningcl** [comment]
adb找不到路径，你看一下指向的是adb目录还是adb文件；
第二个，导入项目，你可以参考一下https://github.com/burningcl/wechat_jump_hack/blob/master/IMPORT.md；

**Comment by myjke123** [comment]
ADB_PATH 如下
 "/Users/HASEE/AppData/Local/Android/sdk/platform-tools/adb";
还有adb已经连接了
C:\Users\HASEE>adb devices
List of devices attached
915436f device
我就是一路参考着来你的这教程来的了

**Comment by burningcl** [comment]
执行一下shell命令“ls /Users/HASEE/AppData/Local/Android/sdk/platform-tools/adb”

**Comment by myjke123** [comment]
java.io.IOException: Cannot run program "ls/Users/HASEE/AppData/Local/Android/sdk/platform-tools/adb": CreateProcess error=2, 系统找不到指定的文件。
好像还是一样

**Comment by burningcl** [comment]
“ls /Users/HASEE/AppData/Local/Android/sdk/platform-tools/adb”结果是什么

**Comment by myjke123** [comment]
额难道不是就在 static final String ADB_PATH = “ls 后直接这样加吗？ 可能作为什么都不懂的小白搞这个还是太难。。刚刚给adb换了下路径没装c盘里了也还是不行，放弃了，不搞了

**Comment by burningcl** [comment]
哈，你是windows用户啊，ADB_PATH就是ADB文件的路径啊

**Comment by lOCKemM** [comment]
不用了。。。我是搞java的，还以为安卓很简单，搞个环境就这么困难


在2018年1月10日 09:47，Jairus Chan<notifications@github.com> 写道：

哈，你是windows用户啊，ADB_PATH就是ADB文件的路径啊
