### ISSUE TITLE
分析算法遇到的问题,求助

### ISSUE THREAD

**Issue by yizeliang** [burningcl/wechat_jump_hack#67]
https://github.com/burningcl/wechat_jump_hack/blob/0acec3fe397a470ba3f0791daf15508e3ca8238e/src/com/skyline/wxjumphack/NextCenterFinder.java#L106
直到 下面while循环结束

昨天试着分析下你的算法,大致的都看明白了,但是有一块不太清楚,没有看懂,不知道是处理什么情况的,希望能够给点提示,非常感谢
或者给解释一下为什么要这样写
大一看这块代码这是一脸懵逼.....

**Comment by yizeliang** [comment]
刚才又看了一遍,看懂了,,,,

**Comment by burningcl** [comment]
哈哈，递归算法改非递归的一种实现。
