### ISSUE TITLE
执行弹跳时，最好加waitFor

### ISSUE THREAD

**Issue by xusanxiang** [burningcl/wechat_jump_hack#68]
adb执行命令后等待的是固定数时间，有时候adb执行速度慢，导致截图时，还没有跳完，拿到的小人还在空中，下次就会over
Process process2 = Runtime.getRuntime().exec(adbCommand);
process2.waitFor();
执行跳的代码改成这个，问题就能解决

**Comment by burningcl** [comment]
更新代码，几天前改掉了
