### ISSUE TITLE
三星s8+ 第一次就直接飞了。。。。

### ISSUE THREAD

**Issue by jinhuiWong** [burningcl/wechat_jump_hack#70]
三星的 s8+ 手机全面屏, 
18.5：9高宽比 
分辨率2220 x 1080 
第一次就直接飞了。。。。
那个系数怎么调都不对。。。。

**Comment by burningcl** [comment]
跳远了就调小一些，跳近了就调大一些。
本来就要慢慢试的，每个机器都不一样。

**Comment by jinhuiWong** [comment]
调到了第一步可以跳到中心点了，可是再跳几步就短了，目前最多就跳到不超过10步。。。

**Comment by burningcl** [comment]
请运行HackTest.java文件，观察标记的位置是否准确。 如果准确的话，根据反馈同学的经验：

   - 请自行调整弹跳系数；
   - 换一根好一点的数据线；

**Comment by inputnow** [comment]
魅族MX4 Pro 分辨率 2560*1536 向上跳没有问题  但是横着跳就飞了 请问这是什么情况

**Comment by burningcl** [comment]
这个游戏应该没有向上跳和横着跳的。。。。
