### ISSUE TITLE
两个块颜色一样的时候会有问题

### ISSUE THREAD

**Issue by kufei88** [burningcl/wechat_jump_hack#73]
两个块颜色一样的时候会有问题
![1](https://user-images.githubusercontent.com/11867647/34914870-70a32236-f956-11e7-8b7a-91edd756ce48.png)

**Comment by burningcl** [comment]
嗯，对，这种情况可能会出现，也没有特别好的解决方案。
我以后会想想办法的。
但是，即使出现这种情况，玩家应该也不会掉下去吧。

**Comment by kufei88** [comment]
当第二块很小的时候会的
