### ISSUE TITLE
mi 6， 找不到x.png

### ISSUE THREAD

**Issue by george-cw** [burningcl/wechat_jump_hack#76]
我的mi6试了发现，有时截图未拷贝完，运行到BufferedImage image = ImgLoader.load(file.getAbsolutePath());，找不到截图。
在前面加上
if (!file.exists()){
       continue;
} 解决了该问题

**Comment by burningcl** [comment]
这是可行的，要不你提交一下你的代码？

**Comment by george-cw** [comment]
可以呀，不用加权限直接可以传吗

**Comment by burningcl** [comment]
提交以后，会有一个pull request，然后我再合并一下就可以。
http://blog.csdn.net/qq_33429968/article/details/62219783
