### ISSUE TITLE
不同分辨率问题

### ISSUE THREAD

**Issue by chenxin061** [burningcl/wechat_jump_hack#81]
荣耀V9， 2560*1440分辨率，识别情况如图：

![image](https://user-images.githubusercontent.com/35479969/34974118-3e54b968-fac6-11e7-8c07-e847f8da836c.png)
![image](https://user-images.githubusercontent.com/35479969/34974123-4757ccc6-fac6-11e7-9dc7-53b087bc8da3.png)
![image](https://user-images.githubusercontent.com/35479969/34974138-5636cb66-fac6-11e7-8ac1-aa0e0a328c8d.png)
![image](https://user-images.githubusercontent.com/35479969/34974141-5a964074-fac6-11e7-9d68-150dfd9970d5.png)
![image](https://user-images.githubusercontent.com/35479969/34974146-63184f58-fac6-11e7-9422-a63bf2e59c1a.png)
![image](https://user-images.githubusercontent.com/35479969/34974149-675fadd6-fac6-11e7-8384-0bd249e2a205.png)

**Comment by burningcl** [comment]
哦。。。原来还会这样。。
我测试用的手机是1080p。
好像，你的手机左右两个点没有找到。我手边没有这样的手机，麻烦你帮忙测试一下。NextPosFinder.java中第77行，‘for (int k = 0; k < 5; k++) {’，将5改为10，试试看。。。
如果有结果，也请告诉我一下。

**Comment by chenxin061** [comment]
我测试了从2到15中的某些值，都只会出现一个绿点一个蓝点，但是k数值越大，配合跳跃系数，准确度越高。另： 我将截图放大很多倍查看过，从肉眼观察来看并不存在三个绿点重合的情况

**Comment by burningcl** [comment]
不是不是，现在你只有一个绿点，就是最上面的顶点。找不到左右两边的点。
麻烦你把你的源图（没有标点识别结果的那种），发几张给我。

**Comment by chenxin061** [comment]
我发几个对应的吧，奇数张原图，偶数张识别图
![5](https://user-images.githubusercontent.com/35479969/34979104-5842c7a6-fadb-11e7-94fa-ad39ca26396f.png)
![5](https://user-images.githubusercontent.com/35479969/34979132-6d68ce50-fadb-11e7-8847-6e5544021f62.png)
![6](https://user-images.githubusercontent.com/35479969/34979156-79f6355e-fadb-11e7-9324-e3d62645254f.png)
![6](https://user-images.githubusercontent.com/35479969/34979165-7dbbc5fa-fadb-11e7-9af4-74cece40fb4c.png)
![11](https://user-images.githubusercontent.com/35479969/34979201-9791a88c-fadb-11e7-880c-589efaa53684.png)
![11](https://user-images.githubusercontent.com/35479969/34979216-9da52f28-fadb-11e7-8066-61f5e0a59cc2.png)

**Comment by burningcl** [comment]
![34979216-9da52f28-fadb-11e7-8066-61f5e0a59cc2](https://user-images.githubusercontent.com/8577280/35131761-03abfae4-fd03-11e7-85bf-817b5f53422e.png)
![34979156-79f6355e-fadb-11e7-9324-e3d62645254f](https://user-images.githubusercontent.com/8577280/35131767-0be04062-fd03-11e7-97c3-80758107fd1f.png)
![34979104-5842c7a6-fadb-11e7-94fa-ad39ca26396f](https://user-images.githubusercontent.com/8577280/35131771-130a7826-fd03-11e7-9cb2-67b2b0791195.png)

**Comment by burningcl** [comment]
不知道是手机个体原因，还是微信改了实现，边界上面有虚点。
我改进了算法，以上是效果。你更新一下代码看看

**Comment by chenxin061** [comment]
基本没问题，log, when!
