### ISSUE TITLE
项目导入无法运行

### ISSUE THREAD

**Issue by GitHubzcc** [burningcl/wechat_jump_hack#82]
![image](https://user-images.githubusercontent.com/31427958/34976421-903d181e-fad1-11e7-8a84-7d0224813d53.png)
项目导出来后hack文件不是可运行文件

**Comment by GitHubzcc** [comment]
![image](https://user-images.githubusercontent.com/31427958/34976890-7e3d3250-fad3-11e7-9253-fbf5c6b73af5.png)
![image](https://user-images.githubusercontent.com/31427958/34976906-951a442c-fad3-11e7-8658-5aefd8a8bb27.png)
文件一导出来就是无法运行

**Comment by burningcl** [comment]
你的导入方式出错了，两种解决方案：
1.  跟着教程再来一次；
2. file -> project struct -> modules，将src选择为Sources目录
