### ISSUE TITLE
无输出文件（图片）问题

### ISSUE THREAD

**Issue by Eternal-Br** [burningcl/wechat_jump_hack#83]
运行一小段时间之后发现，您截图中的输出路径中，在我这里并没有出现任何输出，这是怎么回事啊？

**Comment by Eternal-Br** [comment]
![image](https://user-images.githubusercontent.com/28819440/34988119-8763775c-faf8-11e7-8054-dccac6edcd6e.png)

**Comment by burningcl** [comment]
运行HackTest.java后，output只会输出标识图片

**Comment by shanyouguixi** [comment]
你好，大佬！
     发现有一款工具可以实时将手机画面传给电脑，Total Control。30帧左右，个人觉得手机截图传给电脑有些慢。
这个工具也可以写脚本，获取屏幕颜色等属性，还可以模拟出发事件。应该可以做星途wegoing这种画面变化很快的
游戏的辅助。
如果大佬感兴趣的话可以试试。可以用wifi或者usb连接

**Comment by burningcl** [comment]
cool，这是一个思路。
但是，这个工具，是不是只能在windows上运行？
