### ISSUE TITLE
算法请教

### ISSUE THREAD

**Issue by JKXY** [burningcl/wechat_jump_hack#84]
您好，我是一名Android开发者，我根据你的算法写了一个安卓全自动的辅助软件，做出来后发现在部分手机NextCenterFinder方法有误，猜测是在全面屏的手机截图有问题（会在两边多出空白边），可是不管是修改NextCenterFinder方法取背景参照值方式（ image.getPixel(0, 200);）还是修改图片去除空白边方式，都找不到中心点，现在有点无从下手（本身自己对图像这一块不熟悉），希望能帮助解答一下，万分感谢！参考图：http://oqc1v7fbs.bkt.clouddn.com/jump_1515738529591.png

**Comment by burningcl** [comment]
你好，请问一下，你的手机是什么手机，为何分辨率，如此狭长？而且为什么截图会有空白区域？

**Comment by JKXY** [comment]
三星s8（1080*2220），有空白区域应该是利用MediaProjectionManager服务截图且是曲面屏的原因产生的，我看算法，调整一下取背景参照值点位置，应该就能找到点，不过结果明显不是这样（ps：使用adb不会有空白，而且可以找到正确的中心点）

**Comment by burningcl** [comment]
换句话说，你就是想把这个程序移植到android手机上，应该是用无障碍服务来开发吧。但是，由MediaProjectionManager截图出现了空白，导致识别失败。是这样吧？

**Comment by JKXY** [comment]
嗯嗯，是这样的，在不是曲面屏手机是没问题的，但是在曲面屏因为图片问题识别失败，这也是我想不通的，我感觉按照你写的算法，修改一下参照值点位置应该也是可以识别成功的，但是结果显然不是这样的

**Comment by burningcl** [comment]
你可以修改一下算法，扫到空白点，就continue掉
