### ISSUE TITLE
ADB请教

### ISSUE THREAD

**Issue by kimonic** [burningcl/wechat_jump_hack#87]
adb如何模拟长按事件?
我使用adb shell input tap 250 250   模拟触摸点击事件 ,但是按下去后不会弹起,能请教下是怎么回事么?

**Comment by burningcl** [comment]
没有权限，打开开发者选项，找到“USB调试（安全设置）允许通过USB调试修改权限或者模拟点击”（在miui上是这样的，在其他手机上，应该也是差不多这样）这个开关，打开它；如果这个权限没有授予，则不能正常触发弹跳；
https://github.com/burningcl/wechat_jump_hack/blob/master/IMPORT.md

**Comment by kimonic** [comment]
能给一下长按事件,adb命令的示例么?

**Comment by burningcl** [comment]
adb  shell input swipe %d %d %d %d %d

**Comment by kimonic** [comment]
这个不是滑动的么,设置同一坐标点时,我再模拟器上测试有时无效啊?

**Comment by burningcl** [comment]
最后一个参数表示时长啊

**Comment by burningcl** [comment]
https://zhuanlan.zhihu.com/p/26236061
我就帮你google了下

**Comment by kimonic** [comment]
这个项目Android studio能导入么?

**Comment by burningcl** [comment]
http://blog.csdn.net/xx326664162/article/details/51455313

**Comment by kimonic** [comment]
thank you!
