### ISSUE TITLE
没有Intellij IDEA，Android Studio怎么运行这个项目呢

### ISSUE THREAD

**Issue by DanwayChan** [burningcl/wechat_jump_hack#88]
刚学习安卓的学生党小白，想运行这个程序学习一下。但是只有Android Studio，网上也没找着import Intellij IDEA project到Android Studio的方法，也不知道行不行，请大神解答一下，感谢~

**Comment by DanwayChan** [comment]
或者说在eclipse上运行呢？

**Comment by burningcl** [comment]
http://blog.csdn.net/xx326664162/article/details/51455313
https://jingyan.baidu.com/article/bad08e1e9b60ee09c85121e5.html
