### ISSUE TITLE
如何运行

### ISSUE THREAD

**Issue by LiuC520** [burningcl/wechat_jump_hack#9]
怎么运行呢

**Comment by burningcl** [comment]
看流程那个章节

**Comment by LiuC520** [comment]
错误: 找不到或无法加载主类 Hack,我直接clone你的项目，然后进入src，java com.skyline.wxjumphack
提示找不到主类

**Comment by burningcl** [comment]
这个，我一时说不清，和你ide配置有关。。。。你要不google一下？

**Comment by LiuC520** [comment]
好了，也链接上了adb，我用的是android studio，然后也运行了，但是就是提示 find myPos, fail

Process finished with exit code 0

**Comment by LiuC520** [comment]
可以了，666

**Comment by fuzi1996** [comment]
你没有将src设置为source
http://blog.csdn.net/longforus/article/details/51685621

**Comment by burningcl** [comment]
没有将src设置为source。因为没有iml文件。
需要你自己去import这个项目。
