### ISSUE TITLE
无法识别的情况

### ISSUE THREAD

**Issue by wangxm345566462** [burningcl/wechat_jump_hack#91]
![19](https://user-images.githubusercontent.com/17328090/35092208-a625c438-fc79-11e7-9860-c97e49353190.png)

**Comment by burningcl** [comment]
贴日志

**Comment by wangxm345566462** [comment]
日志暂时没有。这个是存在  左边角被遮挡 影响的结果

**Comment by wangxm345566462** [comment]
531, 459
pos, x: 498, y: 1040
239, 196, 127
271, 236, 172
top, x: 749, y: 789
false
left, x: 2147483647, y: 2147483647
right, x: -2147483648, y: 2147483647
![19](https://user-images.githubusercontent.com/17328090/35130497-22159294-fcfc-11e7-8539-f591917ddebd.png)

**Comment by burningcl** [comment]
把源图发我一下看看。另外，你改过算法没？

**Comment by wangxm345566462** [comment]
第一张图  右键 另存为 ，即使原图 ， 昨天在使用中 遇到过几次。 都是 人物遮挡住 下一个物体。导致识别不到。   以上的日志是 我还原源码之后执行的。  是没有修改过源码的版本

**Comment by burningcl** [comment]
![35092208-a625c438-fc79-11e7-9860-c97e49353190](https://user-images.githubusercontent.com/8577280/35131604-0679eeee-fd02-11e7-85ef-aa239e8ed646.png)

**Comment by burningcl** [comment]
原因是由于，部分手机在渲染的时候，边界有虚点。我在改进了一下，跳过探测到的边界点。
上面是改进后的识别结果。
你更新一下代码试试看。

**Comment by wangxm345566462** [comment]
好的 谢谢。我试下

**Comment by burningcl** [comment]
不知道是手机个体原因，还是微信改了他们的实现。。。

**Comment by burningcl** [comment]
多谢你的反馈
