### ISSUE TITLE
顶点识别问题

### ISSUE THREAD

**Issue by wangxm345566462** [burningcl/wechat_jump_hack#92]
![image](https://user-images.githubusercontent.com/17328090/35101612-1faa57bc-fc9b-11e7-961a-b7ee735056f6.png)

**Comment by burningcl** [comment]
顶点无所谓，关键是左右两边两个点。顶点只是洪泛的入口而已。

**Comment by wangxm345566462** [comment]
我简单 改了下。  其实 中心点的  x   一定是顶点的 x 。 而不需要左右点的 中心点。 这样可以防止左右点检测错误的情况。

**Comment by wangxm345566462** [comment]
左右点  y 轴一定是一致的。    中心点到 左右两点之间的 距离也是一致的。 可以用这个来修正 识别的坐标误差。 比如这个图
修正后：
![image](https://user-images.githubusercontent.com/17328090/35130403-992cc2b8-fcfb-11e7-8d17-5d15388659fe.png)
修正前：
![image](https://user-images.githubusercontent.com/17328090/35130425-c3847344-fcfb-11e7-93db-cb407ea49d5b.png)

**Comment by burningcl** [comment]
中心点的x肯定不需要是顶点的x。因为有可能盒子不是正方体或者圆住体，是有可能为长方体的。
另外，这个标记结果，是我的代码标记的吗？我代码中没有用圆点标记，都是用正方形的。你改过代码了吧。。。。。

**Comment by wangxm345566462** [comment]
对。中心点的标记是我修改过。   圆柱体 顶点因为是一条直线。所以识别到的错误。 如果取到的是 顶部横线。去中心。即是 中心。 我有测试过。所有的图像 中心点，即是顶点中心。 顶点被遮挡的可能非常小。 所以不容易出错。 而左右两个点 被遮挡的 可能性较大

**Comment by burningcl** [comment]
只会被盖住一点。另外，对于这种情况，只要能跳上去就行了。
