### ISSUE TITLE
边界值 ， 顶点识别是错误

### ISSUE THREAD

**Issue by wangxm345566462** [burningcl/wechat_jump_hack#93]
此处应该修改为 
if (r <= minR || r >= maxR || g <= minG || g >= maxG || b <= minB || b >= maxB)
如果MaxRGB 任何一个 达到了255 就不能超越了 
原因是 255 临界值 不可能不超越 

例如下图 顶点识别是错误的
![18](https://user-images.githubusercontent.com/17328090/35131779-1b15a270-fd03-11e7-89bc-0ef9052c0e7f.png)

**Comment by wangxm345566462** [comment]
![18](https://user-images.githubusercontent.com/17328090/35131909-a1348f06-fd03-11e7-835e-43ded1bc5855.png)

**Comment by burningcl** [comment]
不要修改这段代码，去更新宽容度参数。NextCenterFinder.java第47行，‘int t = 16;’。应该是微信调整了背景色的差距。你调调看，如果有合适的参数，告诉我。
