### ISSUE TITLE
求问棋盘Y坐标的识别思路

### ISSUE THREAD

**Issue by 417401901** [burningcl/wechat_jump_hack#99]
水平有限Java有点看不明白，能简单说下识别棋盘Y坐标是怎么做到的么？能识别出三个点感觉好牛

**Comment by burningcl** [comment]
下一个盒子，如果是正方形或者长方形，左右两个角（最左边的点和最右边的点）的连线的中间点就是盒子中心点。
下一个盒子，如果是圆形，最左边的点和最右边的点，两者之间的连线势必是经过圆心的，那中间点就是盒子的中心点。
其实，就是一个非常简单的数学几何原理，计算的成本也非常低。
^-^
